import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/component/Header";
import Footer from "@/app/component/Footer";
import ProviderWrapper from "./ProviderWrapper";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hackathon E-Commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
    <Script
  src="https://cdn.botpress.cloud/webchat/v3.6/inject.js"
  strategy="afterInteractive"
    />

    <Script
  src="https://files.bpcontent.cloud/2026/03/03/16/20260303162426-YG2RW13M.js"
  strategy="afterInteractive"
    />
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderWrapper>
        <Header />
        {children}
        <Footer />
        </ProviderWrapper>
      </body>
    </html>
  );
}

